# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
   adapter: mysql2
   database: solazul_development
   username: bluesun
   password: blueSun2016!
   host: localhost

test:
   adapter: mysql2
   database: solazul_test
   username: billscanner
   password: blueSun2016!
   host: localhost

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
